// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Block
 */
export type Block = {
    /**
     * Block Id
     */
    block_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Page Id
     */
    page_id?: string | null;
    /**
     * Parent Block Id
     */
    parent_block_id?: string | null;
    /**
     * Position
     */
    position: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * BlockCreate
 */
export type BlockCreate = {
    /**
     * Content
     */
    content: string;
    /**
     * Position
     */
    position: number;
    /**
     * Page Id
     */
    page_id?: string | null;
    /**
     * Parent Block Id
     */
    parent_block_id?: string | null;
};

/**
 * BlockUpdateContent
 */
export type BlockUpdateContent = {
    /**
     * Block Id
     */
    block_id: string;
    /**
     * New Content
     */
    new_content: string;
};

/**
 * BlockUpdateParent
 */
export type BlockUpdateParent = {
    /**
     * Block Id
     */
    block_id: string;
    /**
     * New Page Id
     */
    new_page_id?: string | null;
    /**
     * New Parent Block Id
     */
    new_parent_block_id?: string | null;
};

/**
 * DatabaseCreate
 */
export type DatabaseCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Page
 */
export type Page = {
    /**
     * Page Id
     */
    page_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PageCreate
 */
export type PageCreate = {
    /**
     * Title
     */
    title: string;
};

/**
 * PageRename
 */
export type PageRename = {
    /**
     * Page Id
     */
    page_id: string;
    /**
     * New Title
     */
    new_title: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Workspace
 */
export type Workspace = {
    /**
     * Workspace Id
     */
    workspace_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color: string;
};

/**
 * WorkspaceCreate
 */
export type WorkspaceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color: string;
};

/**
 * WorkspaceUpdate
 */
export type WorkspaceUpdate = {
    /**
     * Workspace Id
     */
    workspace_id: number;
    /**
     * New Name
     */
    new_name: string;
    /**
     * New Color
     */
    new_color: string;
};

export type GetPagesDbDbNamePagesGetData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/pages';
};

export type GetPagesDbDbNamePagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPagesDbDbNamePagesGetError = GetPagesDbDbNamePagesGetErrors[keyof GetPagesDbDbNamePagesGetErrors];

export type GetPagesDbDbNamePagesGetResponses = {
    /**
     * Response Get Pages Db  Db Name  Pages Get
     * List of pages retrieved successfully
     */
    200: Array<Page>;
};

export type GetPagesDbDbNamePagesGetResponse = GetPagesDbDbNamePagesGetResponses[keyof GetPagesDbDbNamePagesGetResponses];

export type AddPageDbDbNamePagesPostData = {
    body: PageCreate;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/pages';
};

export type AddPageDbDbNamePagesPostErrors = {
    /**
     * Conflict - Page with this title already exists
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPageDbDbNamePagesPostError = AddPageDbDbNamePagesPostErrors[keyof AddPageDbDbNamePagesPostErrors];

export type AddPageDbDbNamePagesPostResponses = {
    /**
     * Page created successfully
     */
    200: unknown;
};

export type RenamePageDbDbNamePagesPutData = {
    body: PageRename;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/pages';
};

export type RenamePageDbDbNamePagesPutErrors = {
    /**
     * Page not found
     */
    404: unknown;
    /**
     * Conflict - Page with this title already exists
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenamePageDbDbNamePagesPutError = RenamePageDbDbNamePagesPutErrors[keyof RenamePageDbDbNamePagesPutErrors];

export type RenamePageDbDbNamePagesPutResponses = {
    /**
     * Page renamed successfully
     */
    200: unknown;
};

export type DeletePageDbDbNamePagesPageIdDeleteData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: never;
    url: '/db/{db_name}/pages/{page_id}';
};

export type DeletePageDbDbNamePagesPageIdDeleteErrors = {
    /**
     * Page not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePageDbDbNamePagesPageIdDeleteError = DeletePageDbDbNamePagesPageIdDeleteErrors[keyof DeletePageDbDbNamePagesPageIdDeleteErrors];

export type DeletePageDbDbNamePagesPageIdDeleteResponses = {
    /**
     * Page deleted successfully
     */
    200: unknown;
};

export type GetPageDbDbNamePagesPageIdGetData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: never;
    url: '/db/{db_name}/pages/{page_id}';
};

export type GetPageDbDbNamePagesPageIdGetErrors = {
    /**
     * Page not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageDbDbNamePagesPageIdGetError = GetPageDbDbNamePagesPageIdGetErrors[keyof GetPageDbDbNamePagesPageIdGetErrors];

export type GetPageDbDbNamePagesPageIdGetResponses = {
    /**
     * Page retrieved successfully
     */
    200: Page;
};

export type GetPageDbDbNamePagesPageIdGetResponse = GetPageDbDbNamePagesPageIdGetResponses[keyof GetPageDbDbNamePagesPageIdGetResponses];

export type AddBlockDbDbNameBlocksPostData = {
    body: BlockCreate;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/blocks';
};

export type AddBlockDbDbNameBlocksPostErrors = {
    /**
     * Block not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddBlockDbDbNameBlocksPostError = AddBlockDbDbNameBlocksPostErrors[keyof AddBlockDbDbNameBlocksPostErrors];

export type AddBlockDbDbNameBlocksPostResponses = {
    /**
     * Block created successfully
     */
    200: Block;
};

export type AddBlockDbDbNameBlocksPostResponse = AddBlockDbDbNameBlocksPostResponses[keyof AddBlockDbDbNameBlocksPostResponses];

export type GetBlockDbDbNameBlockBlockIdGetData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
        /**
         * Block Id
         */
        block_id: string;
    };
    query?: never;
    url: '/db/{db_name}/block/{block_id}';
};

export type GetBlockDbDbNameBlockBlockIdGetErrors = {
    /**
     * Block not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlockDbDbNameBlockBlockIdGetError = GetBlockDbDbNameBlockBlockIdGetErrors[keyof GetBlockDbDbNameBlockBlockIdGetErrors];

export type GetBlockDbDbNameBlockBlockIdGetResponses = {
    /**
     * Block retrieved successfully
     */
    200: Block;
};

export type GetBlockDbDbNameBlockBlockIdGetResponse = GetBlockDbDbNameBlockBlockIdGetResponses[keyof GetBlockDbDbNameBlockBlockIdGetResponses];

export type GetBlocksDbDbNameBlocksPageIdGetData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: never;
    url: '/db/{db_name}/blocks/{page_id}';
};

export type GetBlocksDbDbNameBlocksPageIdGetErrors = {
    /**
     * Page not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlocksDbDbNameBlocksPageIdGetError = GetBlocksDbDbNameBlocksPageIdGetErrors[keyof GetBlocksDbDbNameBlocksPageIdGetErrors];

export type GetBlocksDbDbNameBlocksPageIdGetResponses = {
    /**
     * Response Get Blocks Db  Db Name  Blocks  Page Id  Get
     * List of blocks retrieved successfully
     */
    200: Array<Block>;
};

export type GetBlocksDbDbNameBlocksPageIdGetResponse = GetBlocksDbDbNameBlocksPageIdGetResponses[keyof GetBlocksDbDbNameBlocksPageIdGetResponses];

export type UpdateBlockContentDbDbNameBlocksContentPutData = {
    body: BlockUpdateContent;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/blocks/content';
};

export type UpdateBlockContentDbDbNameBlocksContentPutErrors = {
    /**
     * Block not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBlockContentDbDbNameBlocksContentPutError = UpdateBlockContentDbDbNameBlocksContentPutErrors[keyof UpdateBlockContentDbDbNameBlocksContentPutErrors];

export type UpdateBlockContentDbDbNameBlocksContentPutResponses = {
    /**
     * Block content updated successfully
     */
    200: unknown;
};

export type UpdateBlockParentDbDbNameBlocksParentPutData = {
    body: BlockUpdateParent;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/blocks/parent';
};

export type UpdateBlockParentDbDbNameBlocksParentPutErrors = {
    /**
     * Bad request - Invalid parent relationship
     */
    400: unknown;
    /**
     * Block not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBlockParentDbDbNameBlocksParentPutError = UpdateBlockParentDbDbNameBlocksParentPutErrors[keyof UpdateBlockParentDbDbNameBlocksParentPutErrors];

export type UpdateBlockParentDbDbNameBlocksParentPutResponses = {
    /**
     * Block parent updated successfully
     */
    200: unknown;
};

export type DeleteBlockDbDbNameBlocksBlockIdDeleteData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
        /**
         * Block Id
         */
        block_id: string;
    };
    query?: never;
    url: '/db/{db_name}/blocks/{block_id}';
};

export type DeleteBlockDbDbNameBlocksBlockIdDeleteErrors = {
    /**
     * Block not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBlockDbDbNameBlocksBlockIdDeleteError = DeleteBlockDbDbNameBlocksBlockIdDeleteErrors[keyof DeleteBlockDbDbNameBlocksBlockIdDeleteErrors];

export type DeleteBlockDbDbNameBlocksBlockIdDeleteResponses = {
    /**
     * Block deleted successfully
     */
    200: unknown;
};

export type GetWorkspacesDbDbNameWorkspacesGetData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/workspaces';
};

export type GetWorkspacesDbDbNameWorkspacesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkspacesDbDbNameWorkspacesGetError = GetWorkspacesDbDbNameWorkspacesGetErrors[keyof GetWorkspacesDbDbNameWorkspacesGetErrors];

export type GetWorkspacesDbDbNameWorkspacesGetResponses = {
    /**
     * Response Get Workspaces Db  Db Name  Workspaces Get
     * List of workspaces retrieved successfully
     */
    200: Array<Workspace>;
};

export type GetWorkspacesDbDbNameWorkspacesGetResponse = GetWorkspacesDbDbNameWorkspacesGetResponses[keyof GetWorkspacesDbDbNameWorkspacesGetResponses];

export type AddWorkspaceDbDbNameWorkspacesPostData = {
    body: WorkspaceCreate;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/workspaces';
};

export type AddWorkspaceDbDbNameWorkspacesPostErrors = {
    /**
     * Workspace not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddWorkspaceDbDbNameWorkspacesPostError = AddWorkspaceDbDbNameWorkspacesPostErrors[keyof AddWorkspaceDbDbNameWorkspacesPostErrors];

export type AddWorkspaceDbDbNameWorkspacesPostResponses = {
    /**
     * Workspace created successfully
     */
    200: Workspace;
};

export type AddWorkspaceDbDbNameWorkspacesPostResponse = AddWorkspaceDbDbNameWorkspacesPostResponses[keyof AddWorkspaceDbDbNameWorkspacesPostResponses];

export type UpdateWorkspaceDbDbNameWorkspacesPutData = {
    body: WorkspaceUpdate;
    path: {
        /**
         * Db Name
         */
        db_name: string;
    };
    query?: never;
    url: '/db/{db_name}/workspaces';
};

export type UpdateWorkspaceDbDbNameWorkspacesPutErrors = {
    /**
     * Workspace not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkspaceDbDbNameWorkspacesPutError = UpdateWorkspaceDbDbNameWorkspacesPutErrors[keyof UpdateWorkspaceDbDbNameWorkspacesPutErrors];

export type UpdateWorkspaceDbDbNameWorkspacesPutResponses = {
    /**
     * Workspace updated successfully
     */
    200: unknown;
};

export type DeleteWorkspaceDbDbNameWorkspacesWorkspaceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
        /**
         * Workspace Id
         */
        workspace_id: number;
    };
    query?: never;
    url: '/db/{db_name}/workspaces/{workspace_id}';
};

export type DeleteWorkspaceDbDbNameWorkspacesWorkspaceIdDeleteErrors = {
    /**
     * Workspace not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkspaceDbDbNameWorkspacesWorkspaceIdDeleteError = DeleteWorkspaceDbDbNameWorkspacesWorkspaceIdDeleteErrors[keyof DeleteWorkspaceDbDbNameWorkspacesWorkspaceIdDeleteErrors];

export type DeleteWorkspaceDbDbNameWorkspacesWorkspaceIdDeleteResponses = {
    /**
     * Workspace deleted successfully
     */
    200: unknown;
};

export type GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetData = {
    body?: never;
    path: {
        /**
         * Db Name
         */
        db_name: string;
        /**
         * Workspace Id
         */
        workspace_id: number;
    };
    query?: never;
    url: '/db/{db_name}/workspaces/{workspace_id}';
};

export type GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetErrors = {
    /**
     * Workspace not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetError = GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetErrors[keyof GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetErrors];

export type GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetResponses = {
    /**
     * Workspace retrieved successfully
     */
    200: Workspace;
};

export type GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetResponse = GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetResponses[keyof GetWorkspaceDbDbNameWorkspacesWorkspaceIdGetResponses];

export type GetDatabasesDatabasesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/databases';
};

export type GetDatabasesDatabasesGetResponses = {
    /**
     * Response Get Databases Databases Get
     * List of databases retrieved successfully
     */
    200: Array<unknown>;
};

export type GetDatabasesDatabasesGetResponse = GetDatabasesDatabasesGetResponses[keyof GetDatabasesDatabasesGetResponses];

export type CreateDatabaseDatabasesPostData = {
    body: DatabaseCreate;
    path?: never;
    query?: never;
    url: '/databases';
};

export type CreateDatabaseDatabasesPostErrors = {
    /**
     * Conflict - Database with this name already exists
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDatabaseDatabasesPostError = CreateDatabaseDatabasesPostErrors[keyof CreateDatabaseDatabasesPostErrors];

export type CreateDatabaseDatabasesPostResponses = {
    /**
     * Database created successfully
     */
    200: unknown;
};
