// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Block
 */
export type Block = {
    /**
     * Block Id
     */
    block_id: number;
    /**
     * Content
     */
    content: string;
    /**
     * Page Id
     */
    page_id?: number | null;
    /**
     * Parent Block Id
     */
    parent_block_id?: number | null;
    /**
     * Position
     */
    position: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * BlockCreate
 */
export type BlockCreate = {
    /**
     * Content
     */
    content: string;
    /**
     * Position
     */
    position: number;
    /**
     * Page Id
     */
    page_id?: number | null;
    /**
     * Parent Block Id
     */
    parent_block_id?: number | null;
};

/**
 * BlockDelete
 */
export type BlockDelete = {
    /**
     * Block Id
     */
    block_id: number;
};

/**
 * BlockUpdateContent
 */
export type BlockUpdateContent = {
    /**
     * Block Id
     */
    block_id: number;
    /**
     * New Content
     */
    new_content: string;
};

/**
 * BlockUpdateParent
 */
export type BlockUpdateParent = {
    /**
     * Block Id
     */
    block_id: number;
    /**
     * New Page Id
     */
    new_page_id?: number | null;
    /**
     * New Parent Block Id
     */
    new_parent_block_id?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Page
 */
export type Page = {
    /**
     * Page Id
     */
    page_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PageCreate
 */
export type PageCreate = {
    /**
     * Title
     */
    title: string;
};

/**
 * PageDelete
 */
export type PageDelete = {
    /**
     * Page Id
     */
    page_id: number;
};

/**
 * PageRename
 */
export type PageRename = {
    /**
     * Page Id
     */
    page_id: number;
    /**
     * New Title
     */
    new_title: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Workspace
 */
export type Workspace = {
    /**
     * Workspace Id
     */
    workspace_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Color
     */
    color: string;
};

/**
 * WorkspaceCreate
 */
export type WorkspaceCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Color
     */
    color: string;
};

/**
 * WorkspaceDelete
 */
export type WorkspaceDelete = {
    /**
     * Workspace Id
     */
    workspace_id: number;
};

/**
 * WorkspaceUpdate
 */
export type WorkspaceUpdate = {
    /**
     * Workspace Id
     */
    workspace_id: number;
    /**
     * New Title
     */
    new_title: string;
    /**
     * New Color
     */
    new_color: string;
};

export type DeletePagePagesDeleteData = {
    body: PageDelete;
    path?: never;
    query?: never;
    url: '/pages';
};

export type DeletePagePagesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePagePagesDeleteError = DeletePagePagesDeleteErrors[keyof DeletePagePagesDeleteErrors];

export type DeletePagePagesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPagesPagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pages';
};

export type GetPagesPagesGetResponses = {
    /**
     * Response Get Pages Pages Get
     * Successful Response
     */
    200: Array<Page>;
};

export type GetPagesPagesGetResponse = GetPagesPagesGetResponses[keyof GetPagesPagesGetResponses];

export type AddPagePagesPostData = {
    body: PageCreate;
    path?: never;
    query?: never;
    url: '/pages';
};

export type AddPagePagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPagePagesPostError = AddPagePagesPostErrors[keyof AddPagePagesPostErrors];

export type AddPagePagesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenamePagePagesPutData = {
    body: PageRename;
    path?: never;
    query?: never;
    url: '/pages';
};

export type RenamePagePagesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenamePagePagesPutError = RenamePagePagesPutErrors[keyof RenamePagePagesPutErrors];

export type RenamePagePagesPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPagePagesPageIdGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: number;
    };
    query?: never;
    url: '/pages/{page_id}';
};

export type GetPagePagesPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPagePagesPageIdGetError = GetPagePagesPageIdGetErrors[keyof GetPagePagesPageIdGetErrors];

export type GetPagePagesPageIdGetResponses = {
    /**
     * Successful Response
     */
    200: Page;
};

export type GetPagePagesPageIdGetResponse = GetPagePagesPageIdGetResponses[keyof GetPagePagesPageIdGetResponses];

export type DeleteBlockBlocksDeleteData = {
    body: BlockDelete;
    path?: never;
    query?: never;
    url: '/blocks';
};

export type DeleteBlockBlocksDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBlockBlocksDeleteError = DeleteBlockBlocksDeleteErrors[keyof DeleteBlockBlocksDeleteErrors];

export type DeleteBlockBlocksDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddBlockBlocksPostData = {
    body: BlockCreate;
    path?: never;
    query?: never;
    url: '/blocks';
};

export type AddBlockBlocksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddBlockBlocksPostError = AddBlockBlocksPostErrors[keyof AddBlockBlocksPostErrors];

export type AddBlockBlocksPostResponses = {
    /**
     * Successful Response
     */
    200: Block;
};

export type AddBlockBlocksPostResponse = AddBlockBlocksPostResponses[keyof AddBlockBlocksPostResponses];

export type GetBlockBlockBlockIdGetData = {
    body?: never;
    path: {
        /**
         * Block Id
         */
        block_id: number;
    };
    query?: never;
    url: '/block/{block_id}';
};

export type GetBlockBlockBlockIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlockBlockBlockIdGetError = GetBlockBlockBlockIdGetErrors[keyof GetBlockBlockBlockIdGetErrors];

export type GetBlockBlockBlockIdGetResponses = {
    /**
     * Successful Response
     */
    200: Block;
};

export type GetBlockBlockBlockIdGetResponse = GetBlockBlockBlockIdGetResponses[keyof GetBlockBlockBlockIdGetResponses];

export type GetBlocksBlocksPageIdGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: number;
    };
    query?: never;
    url: '/blocks/{page_id}';
};

export type GetBlocksBlocksPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlocksBlocksPageIdGetError = GetBlocksBlocksPageIdGetErrors[keyof GetBlocksBlocksPageIdGetErrors];

export type GetBlocksBlocksPageIdGetResponses = {
    /**
     * Response Get Blocks Blocks  Page Id  Get
     * Successful Response
     */
    200: Array<Block>;
};

export type GetBlocksBlocksPageIdGetResponse = GetBlocksBlocksPageIdGetResponses[keyof GetBlocksBlocksPageIdGetResponses];

export type UpdateBlockContentBlocksContentPutData = {
    body: BlockUpdateContent;
    path?: never;
    query?: never;
    url: '/blocks/content';
};

export type UpdateBlockContentBlocksContentPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBlockContentBlocksContentPutError = UpdateBlockContentBlocksContentPutErrors[keyof UpdateBlockContentBlocksContentPutErrors];

export type UpdateBlockContentBlocksContentPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateBlockParentBlocksParentPutData = {
    body: BlockUpdateParent;
    path?: never;
    query?: never;
    url: '/blocks/parent';
};

export type UpdateBlockParentBlocksParentPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBlockParentBlocksParentPutError = UpdateBlockParentBlocksParentPutErrors[keyof UpdateBlockParentBlocksParentPutErrors];

export type UpdateBlockParentBlocksParentPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteWorkspaceWorkspacesDeleteData = {
    body: WorkspaceDelete;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type DeleteWorkspaceWorkspacesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkspaceWorkspacesDeleteError = DeleteWorkspaceWorkspacesDeleteErrors[keyof DeleteWorkspaceWorkspacesDeleteErrors];

export type DeleteWorkspaceWorkspacesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWorkspacesWorkspacesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type GetWorkspacesWorkspacesGetResponses = {
    /**
     * Response Get Workspaces Workspaces Get
     * Successful Response
     */
    200: Array<Workspace>;
};

export type GetWorkspacesWorkspacesGetResponse = GetWorkspacesWorkspacesGetResponses[keyof GetWorkspacesWorkspacesGetResponses];

export type AddWorkspaceWorkspacesPostData = {
    body: WorkspaceCreate;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type AddWorkspaceWorkspacesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddWorkspaceWorkspacesPostError = AddWorkspaceWorkspacesPostErrors[keyof AddWorkspaceWorkspacesPostErrors];

export type AddWorkspaceWorkspacesPostResponses = {
    /**
     * Successful Response
     */
    200: Workspace;
};

export type AddWorkspaceWorkspacesPostResponse = AddWorkspaceWorkspacesPostResponses[keyof AddWorkspaceWorkspacesPostResponses];

export type UpdateWorkspaceWorkspacesPutData = {
    body: WorkspaceUpdate;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type UpdateWorkspaceWorkspacesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkspaceWorkspacesPutError = UpdateWorkspaceWorkspacesPutErrors[keyof UpdateWorkspaceWorkspacesPutErrors];

export type UpdateWorkspaceWorkspacesPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWorkspaceWorkspacesWorkspaceIdGetData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: number;
    };
    query?: never;
    url: '/workspaces/{workspace_id}';
};

export type GetWorkspaceWorkspacesWorkspaceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkspaceWorkspacesWorkspaceIdGetError = GetWorkspaceWorkspacesWorkspaceIdGetErrors[keyof GetWorkspaceWorkspacesWorkspaceIdGetErrors];

export type GetWorkspaceWorkspacesWorkspaceIdGetResponses = {
    /**
     * Successful Response
     */
    200: Workspace;
};

export type GetWorkspaceWorkspacesWorkspaceIdGetResponse = GetWorkspaceWorkspacesWorkspaceIdGetResponses[keyof GetWorkspaceWorkspacesWorkspaceIdGetResponses];
