// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Block
 */
export type Block = {
    /**
     * Block Id
     */
    block_id: number;
    /**
     * Content
     */
    content: string;
    /**
     * Page Id
     */
    page_id?: number | null;
    /**
     * Parent Block Id
     */
    parent_block_id?: number | null;
    /**
     * Position
     */
    position: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * BlockCreate
 */
export type BlockCreate = {
    /**
     * Content
     */
    content: string;
    /**
     * Position
     */
    position: number;
    /**
     * Page Id
     */
    page_id?: number | null;
    /**
     * Parent Block Id
     */
    parent_block_id?: number | null;
};

/**
 * BlockDelete
 */
export type BlockDelete = {
    /**
     * Block Id
     */
    block_id: number;
};

/**
 * BlockUpdateContent
 */
export type BlockUpdateContent = {
    /**
     * Block Id
     */
    block_id: number;
    /**
     * New Content
     */
    new_content: string;
};

/**
 * BlockUpdateParent
 */
export type BlockUpdateParent = {
    /**
     * Block Id
     */
    block_id: number;
    /**
     * New Page Id
     */
    new_page_id?: number | null;
    /**
     * New Parent Block Id
     */
    new_parent_block_id?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Page
 */
export type Page = {
    /**
     * Page Id
     */
    page_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PageCreate
 */
export type PageCreate = {
    /**
     * Title
     */
    title: string;
};

/**
 * PageDelete
 */
export type PageDelete = {
    /**
     * Page Id
     */
    page_id: number;
};

/**
 * PageRename
 */
export type PageRename = {
    /**
     * Page Id
     */
    page_id: number;
    /**
     * New Title
     */
    new_title: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type DeletePagePagesDeleteData = {
    body: PageDelete;
    path?: never;
    query?: never;
    url: '/pages';
};

export type DeletePagePagesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePagePagesDeleteError = DeletePagePagesDeleteErrors[keyof DeletePagePagesDeleteErrors];

export type DeletePagePagesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPagesPagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pages';
};

export type GetPagesPagesGetResponses = {
    /**
     * Response Get Pages Pages Get
     * Successful Response
     */
    200: Array<Page>;
};

export type GetPagesPagesGetResponse = GetPagesPagesGetResponses[keyof GetPagesPagesGetResponses];

export type AddPagePagesPostData = {
    body: PageCreate;
    path?: never;
    query?: never;
    url: '/pages';
};

export type AddPagePagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPagePagesPostError = AddPagePagesPostErrors[keyof AddPagePagesPostErrors];

export type AddPagePagesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenamePagePagesPutData = {
    body: PageRename;
    path?: never;
    query?: never;
    url: '/pages';
};

export type RenamePagePagesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenamePagePagesPutError = RenamePagePagesPutErrors[keyof RenamePagePagesPutErrors];

export type RenamePagePagesPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPagePagesPageIdGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: number;
    };
    query?: never;
    url: '/pages/{page_id}';
};

export type GetPagePagesPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPagePagesPageIdGetError = GetPagePagesPageIdGetErrors[keyof GetPagePagesPageIdGetErrors];

export type GetPagePagesPageIdGetResponses = {
    /**
     * Successful Response
     */
    200: Page;
};

export type GetPagePagesPageIdGetResponse = GetPagePagesPageIdGetResponses[keyof GetPagePagesPageIdGetResponses];

export type DeleteBlockBlocksDeleteData = {
    body: BlockDelete;
    path?: never;
    query?: never;
    url: '/blocks';
};

export type DeleteBlockBlocksDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBlockBlocksDeleteError = DeleteBlockBlocksDeleteErrors[keyof DeleteBlockBlocksDeleteErrors];

export type DeleteBlockBlocksDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddBlockBlocksPostData = {
    body: BlockCreate;
    path?: never;
    query?: never;
    url: '/blocks';
};

export type AddBlockBlocksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddBlockBlocksPostError = AddBlockBlocksPostErrors[keyof AddBlockBlocksPostErrors];

export type AddBlockBlocksPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBlockBlockBlockIdGetData = {
    body?: never;
    path: {
        /**
         * Block Id
         */
        block_id: number;
    };
    query?: never;
    url: '/block/{block_id}';
};

export type GetBlockBlockBlockIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlockBlockBlockIdGetError = GetBlockBlockBlockIdGetErrors[keyof GetBlockBlockBlockIdGetErrors];

export type GetBlockBlockBlockIdGetResponses = {
    /**
     * Successful Response
     */
    200: Block;
};

export type GetBlockBlockBlockIdGetResponse = GetBlockBlockBlockIdGetResponses[keyof GetBlockBlockBlockIdGetResponses];

export type GetBlocksBlocksPageIdGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: number;
    };
    query?: never;
    url: '/blocks/{page_id}';
};

export type GetBlocksBlocksPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBlocksBlocksPageIdGetError = GetBlocksBlocksPageIdGetErrors[keyof GetBlocksBlocksPageIdGetErrors];

export type GetBlocksBlocksPageIdGetResponses = {
    /**
     * Response Get Blocks Blocks  Page Id  Get
     * Successful Response
     */
    200: Array<Block>;
};

export type GetBlocksBlocksPageIdGetResponse = GetBlocksBlocksPageIdGetResponses[keyof GetBlocksBlocksPageIdGetResponses];

export type UpdateBlockContentBlocksContentPutData = {
    body: BlockUpdateContent;
    path?: never;
    query?: never;
    url: '/blocks/content';
};

export type UpdateBlockContentBlocksContentPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBlockContentBlocksContentPutError = UpdateBlockContentBlocksContentPutErrors[keyof UpdateBlockContentBlocksContentPutErrors];

export type UpdateBlockContentBlocksContentPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateBlockParentBlocksParentPutData = {
    body: BlockUpdateParent;
    path?: never;
    query?: never;
    url: '/blocks/parent';
};

export type UpdateBlockParentBlocksParentPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBlockParentBlocksParentPutError = UpdateBlockParentBlocksParentPutErrors[keyof UpdateBlockParentBlocksParentPutErrors];

export type UpdateBlockParentBlocksParentPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
